apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "webproxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "webproxy.name" . }}
    chart: {{ template "webproxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "webproxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "webproxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: squid
              containerPort: 3128
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: squid
          readinessProbe:
            tcpSocket:
              port: squid
          volumeMounts:
            - mountPath: /etc/squid3/
              name: squid3          
          resources:
{{ toYaml .Values.resources | indent 12 }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - {{ template "webproxy.name" . }}
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: squid3
          configMap:
            name: {{ template "webproxy.fullname" . }}
            items:
            - key: conf
              path: squid.conf
            - key: htpasswd
              path: passwords
