apiVersion: v1
kind: Service
metadata:
  name: {{ template "webproxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "webproxy.name" . }}
    chart: {{ template "webproxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.service.ssl_cert_arn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.hostname }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: squid
      protocol: TCP
      name: tcp
  selector:
    app: {{ template "webproxy.name" . }}
    release: {{ .Release.Name }}
